travis:
  secure:
    BINSTAR_TOKEN: CX1ZJBkItr/xmJGtDPA45IYlmTPx1QaYO0AvlsJqT0GPYQotFCMiVRCDCTENWjFq7gxcBr3oo+bhwlWn6CfChfTu/9qXriW0362d29AH50mdrN3sBoKnmgGa763d+NyzOThhBbypY/Nv5aEzZb2LsFDcjmoogi84m6KpINV3uu7XqFeIkrYmUR4A41tYruuO+QkmjBGNc8H36xOJiDxFctznCz1NoMxvjRo9Zgn04m+HXUe7+mI2S0aE4bucFEaW77+BhcIE0umYfRCeMtaTjR/N8976gyfTSJTq7WcChz4i+ikFPfybdNorgjKea7um/7sun5fdMhmc0uw6KOiwUqmy8pssaN2JJKidbCHklRiILAf3+cW3RuxsTCCwdkjBWtFlr/vaLd5A01DddBJXq6Vx3UkP2OvFHguR0tN31lVoH9Pj5C6NZX47A0PbZi81rEONjP/H9dE01j/2RLfzZIe8DBcTqLsK+XdXRH01OhWUJExe9t5dpXraLtbXosfyib3IsXzFRvXOyavCt2y4hQIxEM+PPUgNwaB+JWlw0JHy32HevN9oHp0UPO6E/V/94VJG5OWaJUDJ5FPwAwQeCW6opHeurMFO4hKdMMf5s1o70EHXHZoZW8RDvB7Nowt6jYiIs7wI3/o0ETg6JnIVQfYOnNCVe8Hne5l0rNbDCQI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
