travis:
  secure:
    BINSTAR_TOKEN: Hw/5E3qgtS/0bRUmcdW3z1o4Gl1yNzU4qT5v6+qKrfFZL7hZOlnvv9m+kXZebVPkVK0s3eaMo6AmW4CcI3D0/NLJWNaWlCQkWVqLMxLBasQGtyy47EiSWmcCwQgHuOgEb8NT6tsqyMK914fMyuXi/qlmlurWNVyMd8tWsQaRG6a88jPA2FvvNbDUS+5b+r//FOVmrjuIy0v56Thdvfd+wUM6rQNZsVNjq0iAT3YJ+Z19QzNguqWZpkjc8Nl4IsLXxBpaW/zmwh0jWIpTH+Yy0uQN8rKgulQ2//u1TjUVjkfO9hNnlKXKQ3SKUqFAHAT3+UbnRbVvgwZ6TFswg0XjgAtT6KHWAEeWyscykp7KLmpGvhhI7hwotSCq6s0ykTMLNC4URFkYGfr6o/whfFL//Iy0s1Ryeo1OTtM69v6epndNL+dOgkaH9JDEVmaAX3zPLjk/+pZQCOZ1BCx9sPtjxdhKSTca62LLFdssrouk0TepFqvb+FqfzBbc0iPJhGxBwmZzXy0/vrLyjum0Lx3VF1NT0i6WVb16iwtVXm2I9aa0+e9JUjwrqDrrgiYqCRQe5UUvwBrdwo/WJX+/5wbqlDdvxcyR9VBezTkq5KM6DNDJRXjR9VrukhYsHgeE63y8XhlR/p2zdEJJ2LPES2mb+dMvJ+hXhylECKvd0eRYxcw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
