travis:
  secure:
    BINSTAR_TOKEN: ktSRrYJuI+AXZM2qefnCQFrh7N5CYKxT/8mdNZLVJRtHBs8UO2smAfJtP9fXRFL4k4op1hAHIK99pZpRkhzXY4Eh6+VXitNvYw9G99BX8JAseHbMtNYxrQ5WW0TEIujmvcAkBCkmJ/3lseHKqFFnMh8xmFx32bUsnZTzTdjz3hc4i6T+Nuf2qZLiKnScAOC18WJW+YeAkqL7z7G4tAd6C0LfgAdRUeun1RfxTsKsZ+9G/aeZjirZyyeQVR4OGHrk0uX82WzAWJ+QOaM/qc6AUYp4s9QInpXw2eLO7EAtaWtsmPUghx6yqyDdRKka4L/LDOnrz3/U/p+kxxNla/8Pn1dRK53jXPDnfiE28KR4b1+4sgsDXMjLK22pjy/Fwy8oPBErBm2zEzC7zkiM6c0WDrrTZK+3zDBa/EuBJlqBT/mKOeDFSSEe1ZO4o8RQhdZcXCJyEElVqm6kdjhgQ6u/OPWk9RWUWviofv++WEfUpxChNizbt7qiCR2sVpsqlKqgiyYYSXwt6Bnt32rfDG/i15K3ULSn89RFUccpisFDbUKh1UAqLhiBELs+y8vAulJz+3nCvD56Y6m21+8E8FcKm56R8cpE8rtjLvhF2PJdp6NrmspNVkD942YLjuqSQoHUn5PbanZvajVbKdViTW+VhAg6zdxBX6vmoXSca6qARyU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
