travis:
  secure:
    BINSTAR_TOKEN: F9HQoozqH4ESPQdTIufkbNhCBzYnArA8updtln1j95si/pIG5n00q9wXrjI3zTHTVvi5yTkQr2W2Ywre3y3PBwosZli1PxRqFhLtJ5XQsBq1UYlqG9E0LLI/z6/DeSMLGN8Pqfs/DBAioTk8drQ18iFoZOeIF2NFXDPq5n84Rt/Duflx0ltwXOkQthm3RYXToronxeKNr846QdwTj/Td2Rl32yBtV/pjbK1GTr5/cGzf+Su8XnitLFzYNGz5UvJqMH5iMFo3Uh5gN/ANgri7eNQ5WTgPnzVSHiP7t/d7b/EwcLHLCmWZPVPMHAHbdwXgqhkrwoM/XhkcD66pCnGLwX08ufnhbdvEI+HGnv5hQuhvVQ4aCCv+8SIzRpamZluinekpqyd2spX5Haj3w+c3bvH2QvCogKzWW27jAwrjwWZkizUH3gmFC9dbSTth1aFKzZKJzTozpjtg15Fuio+Gftjaz97BFcyj9z1HcxMGgovATodf1Pjzb0NYj4ChTEFpMDon3eJfutxuN//iglgbKkCvexqfdxl17h8t0+AaWRUMkVFV51ctzrx4w1c+ZXP0y+ixM+tenZlEOJdEF6Oc9XIKkXFDtR7/du1lVfXWA9vhIfjiGWaBu35guh+2/dwwqJqQLra1rsAmHivpILIOcMGSOchp9XMN9YmhRPHKZew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
