travis:
  secure:
    BINSTAR_TOKEN: i1lINxy/6Pq6eQBFhEyFNayTgEYQJesVd2xcyHQc7auqEcE7DuDuBNhXgvI+np+nQ99sOx5OIuzS8UrIXjWnnXGQMkICyWYITe6sAeCjAcr49GkjsNNuIkPcBKNQEAEs5s58cy6nZTallpaCMk7mQ7WofZWtvDXt51R+niClL/9Lz9gLAW9gGQiKA8Gcf3kyKa+VPRpb8e/REmDBRpZHP4JsvOip+PWqzOf+VPM/VtuxQYkCVFTqCAI+nvk6/a6njTB86ymlOagpWfkZCfJW5SGaI91Gum91XUm4/uDGJVKhgFRz3cCtkvQzqPRcnmenQpNlIMmfYA1TIAvMuIuI0wA0N+9dDeTac/RXHWoBqALryWIPc0msCpMFBiydXBJPQhEPrqc0tqOdmQkCKg1ig3fu6PfJw5IRci8aj02tU2sfJUwG2U7vNzeqK3gohg2yc/MuTTwAyVZtEKCioe4jR6ZWyORLRdg88PQCtSP1pFQR8sFLKSfnhf6T0L3ww16FlvgueAgObGM5mU2Akdtrz3+AGnDKLj6D0AzFdE4svgYsfO4ae4Z9XvI7drhIZyaM0HsEBFWqt12MC6M7oMWV+OLdAd4L1GVjwQquFxy9WTcVndK2WjKIkc0HWjW9iL5xeYKFbzw5tICbbQXhvH1IGax0uBHRJZCXk9jOd242YyU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
